### ISSUE TITLE
Advice about a GPU code

### ISSUE THREAD

**Issue by felipeZ** [NLeSC/gpu-sig#1]
I have written together with Nico a C++ code to offload the matrix-matrix multiplication of [eigen3](http://eigen.tuxfamily.org/index.php?title=Main_Page) to gpu using `cublas`. I would really appreciate if any of you could give me your opinion and suggest me further improvements.
The code is [here](https://github.com/NLESC-JCER/EigenCuda) and the import function is this [template](https://github.com/NLESC-JCER/EigenCuda/blob/master/include/eigencuda.hpp).

**Comment by benvanwerkhoven** [comment]
I'd be glad to help. I should have some time this afternoon at 15:00. In which building will you be?

**Comment by felipeZ** [comment]
That is great @benvanwerkhoven! I am at eScience building at the second floor

**Comment by benvanwerkhoven** [comment]
Quick question: what machine are you using for development? I noticed the code now requires a newer GCC version than is installed on the DAS5.

**Comment by felipeZ** [comment]
I am testing at *cartesius*. I am imposing `CXX 14` on the compiler, but I think we can relax it to `CXX 11`

**Comment by benvanwerkhoven** [comment]
I think this issue, which is about one and half years old has been resolved. Please re-open if there's any issue left.
