### ISSUE TITLE
non-informative error compile against cublas

### ISSUE THREAD

**Issue by felipeZ** [NLeSC/gpu-sig#4]
I have found the following error while compiling an application using `cublas`:
```
/usr/include/cublas_api.h(72): catastrophic error: cannot open source file "driver_types.h"
  #include "driver_types.h"
```
Could someone please help me with that error?

**Comment by isazi** [comment]
Hey Felipe, did you see this forum post?

https://devtalk.nvidia.com/default/topic/1023093/cuda-setup-and-installation/driver_type-h-not-found/

**Comment by isazi** [comment]
Maybe that file is installed by a package different than cublas

**Comment by felipeZ** [comment]
Hey Alessio, thanks for the link! I found the issues, it was a linking problem in my CMake configuration file.
