### ISSUE TITLE
Profiling GPU with Nsight and Conda

### ISSUE THREAD

**Issue by felipeZ** [NLeSC/gpu-sig#6]
Hi All,
I am trying to profile a machine learning code for quantum chemistry called [QMCTorch](https://github.com/NLESC-JCER/QMCTorch) that is developed by Nicolas Renaud. The code uses [Pytorch](https://pytorch.org/) and it needs to be installed using Conda.
The [Nsight Compute GUI](https://developer.nvidia.com/nsight-compute) provides me with the following command line to profile the code:
```bash
/usr/lib/nsight-compute/target/linux-desktop-glibc_2_11_3-x64/nv-nsight-cu-cli --export "/home/user/Primer/Python/QMCTorch/profile.txt" --force-overwrite --target-processes application-only --kernel-regex-base function --launch-skip-before-match 0 --section ComputeWorkloadAnalysis --section InstructionStats --section LaunchStats --section MemoryWorkloadAnalysis --section MemoryWorkloadAnalysis_Chart --section MemoryWorkloadAnalysis_Tables --section Occupancy --section SchedulerStats --section SourceCounters --section SpeedOfLight --section WarpStateStats --sampling-interval auto --sampling-max-passes 5 --sampling-buffer-size 33554432 --profile-from-start 1 --clock-control base --apply-rules "/home/user/miniconda3/envs/qmc/bin/python" ch4.py
```

The problem is that when I try to run aforementioned command I got the following error:
```
==ERROR== Error: ERR_NVGPUCTRPERM - The user does not have permission to access NVIDIA GPU Performance Counters on the target device 0. For instructions on enabling permissions and to get more information see https://developer.nvidia.com/ERR_NVGPUCTRPERM  
```
According to the [Nsight Compute documentation](https://developer.nvidia.com/nvidia-development-tools-solutions-err-nvgpuctrperm-nvprof) the issue should be solved by running the code as *root*. But If I run that previous command as root, Conda since to get confused about the environment and Python doesn't find the library dependecies:
```python
Traceback (most recent call last):
  File "ch4.py", line 3, in <module>
    from qmctorch.wavefunction import Orbital, Molecule
  File "/home/felipe/Primer/Python/QMCTorch/qmctorch/wavefunction/__init__.py", line 4, in <module>
    from .wf_orbital import Orbital
  File "/home/felipe/Primer/Python/QMCTorch/qmctorch/wavefunction/wf_orbital.py", line 3, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
```

Do you have any advice about how to solve this issue?

**Comment by benvanwerkhoven** [comment]
Hi Felipe!

Thanks for contacting! Are you using your local machine for this? I suppose you are since you have root access. You can try to follow the instructions on this page to allow all users access to the performance counters:
https://developer.nvidia.com/nvidia-development-tools-solutions-ERR_NVGPUCTRPERM-permission-issue-performance-counters

``modprobe nvidia NVreg_RestrictProfilingToAdminUsers=0``

Let me know if that worked.

Best,
Ben

**Comment by felipeZ** [comment]
@benvanwerkhoven  the `modprobe` command doesn't seem to work for me. Do I need to log out? or run it as sudo?

**Comment by benvanwerkhoven** [comment]
Just for the sake of documenting what happened here. Felipe and I had a brief call and we managed to resolve the issue.

**Comment by Sakurag1l** [comment]
I also have the same problem. the `modprobe` command doesn't seem to work for me.
